"""Registration edits

Revision ID: 479d6fcd3f0a
Revises: 9c14969c770f
Create Date: 2017-05-10 11:23:19.954047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479d6fcd3f0a'
down_revision = '9c14969c770f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
