"""MFA enabled flag

Revision ID: b3c1dc1033b0
Revises: df5b3b0392fc
Create Date: 2017-05-21 16:09:06.262170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c1dc1033b0'
down_revision = 'df5b3b0392fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mfa_enabled')
    # ### end Alembic commands ###
