"""Remove broken news post constraint

Revision ID: df5b3b0392fc
Revises: dbc51d3a4f53
Create Date: 2017-05-13 15:38:56.329265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5b3b0392fc'
down_revision = 'dbc51d3a4f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_post_user_id_key', 'news_post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('news_post_user_id_key', 'news_post', ['user_id'])
    # ### end Alembic commands ###
