"""Unique email codes

Revision ID: e6937aa2f743
Revises: da961d77314e
Create Date: 2017-05-07 14:41:04.134656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6937aa2f743'
down_revision = 'da961d77314e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'email_code', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_code', type_='unique')
    # ### end Alembic commands ###
